eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
  instance:
    hostname: localhost
server:
  port: 9005
spring:
  application:
    name: eureka-server
